# -*- coding: utf-8 -*-
"""Quiz 1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1yK_4mAiYgM0V9CmcTTixV46jLHHpITJf

### Quiz 2
"""

Question 01 - Roll two dice and X is the sum of faces values. If we roll 
them 5 times and get 2,3,4,5,6. Which of the following is/are true about X?
# answer: X is a random variable

Question 2 - Roll two dice and X is the sum of faces values. If we roll them 5 
times and get 2,3,4,5,6 What do we know about X?
# answer: We have 5 observations of x

Question 3 - Roll two dice and X is the sum of faces values. If we roll them 5 
times and get 2,3,4,5,6. X is a ________ random variable.
# answer: Discrete

Question 4 - Why do we use relative frequency instead of frequency?
# answer: Relative frequency can be used to compare the ratio of values between 
# difference collections with difference number of values

Question 5 - What can we say about relative frequency when we have large number of trials?
# answer: Relative frequency becomes approximately the distribution of the 
# corresponding random variable

Question 6 - What is the notion of  "95% Value at Risk" ?
# answer: 95% VaR measures the amount of investment you can lose, at the worst 5% scenario

Question 7 - In the lecture video, we mentioned the calculation of continuous 
random variable is based on the probability density function. 
Given a probability density function, f(x) = 1/100, what is the probability 
P(10<X<20), where X~Uniform[0, 100]?
# answer: (20- 10) * 1/100

Question 8 - What methods should we use to get the cdf and pdf of normal distribution?
# answer: norm.cdf() and norm.pdf() from scipy.stats

Question 9 - Which additional library should we import when we want to calculate log daily return specifically?
# answer: Numpy 

Question 10 - What is the distribution of stock returns suggested by Fama and French in general?
# answer: Close to normal distribution but with fat tail