# -*- coding: utf-8 -*-
"""Quiz03.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1yK_4mAiYgM0V9CmcTTixV46jLHHpITJf

### Quiz 3
"""

Question 1 - What is true about sample and population?
# answer: Sample is a subset of population which is randomly draw from population

Question 2 - You have a DataFrame called ‘data’ which has only one column ‘population’.

data = pd.DataFrame()
data[‘population’] = [47, 48, 85, 20, 19, 13, 72, 16, 50, 60]  

How to draw sample with sample size =5, from a ‘population’ with replacement?    

(Hint: You can modify the code illustrated in the Jupyter Notebook "Population and Sample" after Lecture 3.1)
# answer: data[‘population’].sample(5, replace=True)

Question 3 - Why is the degrees of freedom n-1 in sample variance?
# answer: The degrees of freedom in sample variance is constrained by the sample mean

Question 4 - What does Central Limit Theorem tell you about the distribution of sample mean?
# answer: The distribution of sample mean follows normal distribution with very large sample 
# size follows normal distribution regardless of the population distribution.

Question 5 - Suppose we have 3 independent normal random variables X1, X2 and X3:

What is the distribution of X1 + X2 + X3?
# answer: Mean and variance of X1, X2 and X3 are added up

Question 6 - Why do we need to standardize sample mean when making inference?
# answer: The standardized distribution of sample mean follows N(0,1) which is easier to make inference

Question 7 - What can a 95% confidence interval of daily return of an investment tell you?
# answer: With 95% chance this interval will cover the mean of daily return

Question 8 - Check the Juypter notebook of 3.3 Sample and Inference. What is the confidence interval of this exercise?
# answer: [-0.000015603, 0.001656]

Question 9 - When do you reject a null hypothesis with alternative hypothesis μ>0 with significance level α?
# answer: p value is smaller than α;  z < z_(1-α)

Question 10 - When doing analysis of stock return, you notice that with 95% confidence interval, 
the upper bound and lower bound are negative. Base on this data, what can you tell about this stock?
# answer: There is 95% chance of which the mean return of this stock is negative