# -*- coding: utf-8 -*-
"""4.6.Quiz04.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1yK_4mAiYgM0V9CmcTTixV46jLHHpITJf

### Quiz 4
"""

Question 1 - Why do you use coefficient of correlation, instead of covariance, when calculating the association between two random variables?
# answer: Covariance can be affected by the variance of individual variables, but coefficient of correlation is rescaled by variance of both variables

Question 2 - What is the range and interpretation of coefficient of correlation?
# answer: From -1 to 1, -1 means perfect negative linear relationship and 1 means perfect positive linear relationship

Question 3 - Is LSTAT a significant predictor of MEDV at significance level 0.05?
# answer: Yes, because the p value of b_1 is smaller than 0.05

Question 4 - What is the percentage of variation explained by the model?
# answer: 0.54

Question 5 - How to check if a linear regression model violates the independence assumption?
# answer: Durbin Watson test

Question 6 - If any of the assumptions of linear regression model are violated, we cannot use this model to make prediction.
# answer: False

Question 7 - We have a variable ‘formula’ which store the names of predictors and target. 
How should you modify this ‘formula’ if you want to drop the predictor ‘daxi’?
# answer: formula = ‘spy~aord+cac40+nikkei+dji’

Question 8 - What is the most significance predictor for ‘SPY’?
# answer: arod

Question 9 - What does it mean if you have a strategy with maximum drawdown of 3%?
# answer: During the trading period, the maximum gain from the previous peak of your portfolio value is 3%

Question 10 - How can you check the consistency of your trading strategy?
# answer: Define some metric for evaluating your strategy, eg Sharpe Ratio, maximum drawdown. 
# Then split your data into train set and test set and check if your strategy can generate positive 
# return using both train set and test set.